name: Data Collection

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/30 * * * *'

env:
  SERVICE_URL: ${{ secrets.SERVICE_URL }}
  DEVICE_ID: ${{ secrets.DEVICE_ID }}
  COLLECTOR_KEY: ${{ secrets.COLLECTOR_KEY }}

jobs:
  scheduled:
    runs-on: ubuntu-latest
    environment: collection
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Setup deno 1.26.x
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.26.x
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm i -g @squoosh/cli
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: 'https://raw.githubusercontent.com/grevend/fontys-piot-flatdata-test/main/.github/placeholder/empty.json'
          downloaded_filename: 'data.json'
          postprocess: 'collect.ts'
